trainer:
  learning_rate: 1e-4
  gpu: 1
  num_worker: 0
  train_dataset: C:\Users\zihan\Desktop\visualDet3D\visualDet3D\visualDet3D\data\kitti_obj\training
  valid_dataset: C:\Users\zihan\Desktop\visualDet3D\visualDet3D\visualDet3D\data\kitti_obj\training
  test_dataset: C:\Users\zihan\Desktop\visualDet3D\visualDet3D\visualDet3D\data\kitti_obj\testing
  train_split: C:\Users\zihan\Desktop\visualDet3D\visualDet3D\visualDet3D\data\kitti\chen_split\train.txt
  valid_split: C:\Users\zihan\Desktop\visualDet3D\visualDet3D\visualDet3D\data\kitti\chen_split\val.txt
  test_split: C:\Users\zihan\Desktop\visualDet3D\visualDet3D\visualDet3D\data\kitti\test_split\test.txt
#  train_dataset: D:\DATASET\KITTI\3DDetection\data_object_image_2\training
#  valid_dataset: D:\DATASET\KITTI\3DDetection\data_object_image_2\training
#  valid_split: temp/det3d/total_split_val.txt
#  train_split: temp/det3d/total_split_train.txt
#  train_split: temp/kitti_split/chen_split_train.txt
#  valid_split: temp/kitti_split/chen_split_val.txt
#  valid_split: temp/kitti_split/debug_split_val.txt
#  train_split: temp/kitti_split/debug_split_train.txt

#  train_dataset: C:\Users\yilin\Documents\Tencent Files\1787609016\FileRecv\training\training
#  valid_dataset: C:\Users\yilin\Documents\Tencent Files\1787609016\FileRecv\training\training

  batch_size: 8
  auto_lr_find: false
  #resume_from_checkpoint: #C:\Users\zihan\Desktop\checkpoints\epoch=53-step=47087.ckpt
  resume_from_checkpoint: #C:\Users\zihan\Desktop\python\src\3d_detection\lightning_logs\version_173\checkpoints\epoch=47-step=41855.ckpt
  evaluate: false
  running_sanity_check: false
det_3d:
  preprocessed_path: temp/kitti_test2
  compute_anchor: true
  score_threshold: 0.5
  test_score_threshold: 0.75
  rotate_pitch_when_project: false

anchor:
  #pyramid_levels: [4]
  #sizes: [24]
  #v_strides: [1]
  pyramid_levels: [3, 4, 5, 6, 7]
  sizes: [16, 32, 64, 128, 256]
  v_strides: [1, 1, 1, 1, 1]
  #v_strides: [8, 16, 32, 64, 128]


#  ratios: [.125, .25, .5, 1, 2., 4., 8.]
  ratios: [.5, 1, 2]
  #ratios: [.5, 1, 2]
  #scales: [0.5, 1., 2., 3., 4., 5., 6., 7., 8., 9., 10., 11., 12., 13., 14., 15.]
  #scales: [1., 1.18920712, 1.41421356, 1.68179283, 2., 2.37841423, 2.82842712, 3.36358566, 4., 4.75682846, 5.65685425, 6.72717132, 8., 9.51365692, 11.3137085, 13.45434264]

model:
  img_shape_x: 1280
  img_shape_y: 288


hydra:
  run:
    dir: .
  output_subdir: null
#  job_logging: disabled
#  hydra_logging: disabled